name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      base: cpp_msbuild/
      run: test.exe
    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - run: | 
        cd $base
        msbuild /p:Configuration=Release
        ./x64/Release/$run
